# specify the language and which version
language: python
python:
  - "2.7_with_system_site_packages"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: python setup.py test